### ISSUE TITLE
qt_5_private_api not defined in file libqt5gui.so.5

### ISSUE THREAD

**Issue by dogukangulyasar** [Joomlax/Intro-To-Embedded#1]
I get this error when I try the run my cross-compiled application on the Raspberry Pi 3 B+. I cross-compile my application used qmake and I get this error.

**Comment by dogukangulyasar** [comment]
I realized that the problem is caused by Qt version conflicts or the library conflicts inside of the raspberry. I fixed this problem by re-imaging the raspbian and start over the whole process. I did correctly these sections. So I think you should be careful at these steps:

`sudo apt-get build-dep libqt5gui5`
This code can not install the libqt5gui5 on its own. You must need to be careful with the output of this code. The terminal will give you some warnings which can be:

`Unhalted packages ... libgles-2-dev ...`

You need to install all packages that is given by try installing libqt5gui5 package's warnings. After that problem, you need to becareful at that point:

`sudo mv /usr/lib/arm-linux-gnueabihf/libEGL.so.1.0.0 /usr/lib/arm-linux-gnueabihf/libEGL.so.1.0.0_backup`
`sudo mv /usr/lib/arm-linux-gnueabihf/libGLESv2.so.2.0.0 /usr/lib/arm-linux-gnueabihf/libGLESv2.so.2.0.0_backup`
`sudo ln -s /opt/vc/lib/libEGL.so /usr/lib/arm-linux-gnueabihf/libEGL.so.1.0.0`
`sudo ln -s /opt/vc/lib/libGLESv2.so /usr/lib/arm-linux-gnueabihf/libGLESv2.so.2.0.0`
`sudo ln -s /opt/vc/lib/libbrcmEGL.so /opt/vc/lib/libEGL.so`
`sudo ln -s /opt/vc/lib/libbrcmGLESv2.so /opt/vc/lib/libGLESv2.so`

You need to do try-cath technique there. The first one is the standard one but other ones can be changeable and you need to track these paths and find the written packages inside of these paths. If you can not find just do :

` find / -name libEGL* -type f`
 ` find / -name libGLESv2* -type f`

And link these outputs to the correct places:

`ln -fs /path/to/lib/libEGL.so /usr/lib/arm-linux-gnueabihf/libEGL.so`
`ln -fs /path/to/lib/libEGL.so /usr/lib/arm-linux-gnueabihf/libEGL.so.1`
`ln -fs /path/to/lib/libGLESv2.so /usr/lib/arm-linux-gnueabihf/libGLESv2.so`
`ln -fs /path/to/lib/libGLESv2.so /usr/lib/arm-linux-gnueabihf/libGLESv2.so.2`


This will fix your problem.

**Comment by yakupbeyoglu** [comment]
Generally, GUI problems occurs with missing libEGL at this point we need to careful on cross-compile creation process as well for both host and embedded. Thanks for solution report.
